title = Luanti eSports
name = luanti_esports
description = A fast-paced hitscan Team Deathmatch base game for Luanti with building and storm mechanics.
allowed_mapgens = singlenode
author = Jaden
release = 1
